function [ratio,cas,dir] = cascadesub4_TC3(E_vib,nquanta,ovlp,...
    parameters_laser,parameters_material,iomega)
% Compute third order cascade response functions
%   wviball             : vibrational energies for each basis state
%   ovlp                  : overlap integrals between basis states.
%   nquanta           : number of quanta
%   parameters      : Material parameters
%
%   seq                  : Sequential third order cascades
%   par                  : Parallel third order cascades
%   cascades2d    : Sum of sequential and parallel third order cascades
%   direct2d          : Direct fifth order signal

%% COMPUTE BOLTZMANN POPULATIONS
kT=200; % kT in cm^-1
% Compute array of 
boltz_factor=exp(-E_vib/kT);
% Compute partition function
partition_func=sum(boltz_factor);
% Compute boltzman populations
boltz_pop=boltz_factor/partition_func;

%% Laser parameters
dt=parameters_laser.dt;
nt=parameters_laser.nt;
w_L=parameters_laser.w_L;

%% Material parameters
% Electronic dephasing rate
gamma_eg=parameters_material.gamma_eg;
% Vibrational dephasing rate
gamma_vib=parameters_material.gamma_vib;
% Electronic energy gap
weg=parameters_material.weg;
% Vibrational frequencies Solute
wvib=parameters_material.wvib;
% Vibrational frequencies Solvent
wsolv=parameters_material.wsolv;

%%
iq=nquanta;
% Speed of light in cm/fs
c=2.998E-5;%
% 2pi*c
r2w=2*pi*c;%0.0001885;%

% Vibrational energy levels Solvent
wsolv=(0:iq+1/2)*wsolv;

% Vibrational energy gaps Solute
[col,row]=meshgrid(E_vib,E_vib);
w=row-col;

damp=gamma_vib*c;

%
kjD=1:nt;
tauD=(kjD-1)*dt;
ntC=nt*2;
kjC=1:ntC;
tauC=(kjC-1)*dt;

% Initialize terms of response function to 0
r1=complex(zeros(nt,nt,iq,'double'));
r2=r1;r3=r1;r4=r1;
r5=r1;r6=r1;r7=r1;r8=r1;
r9=r1;r10=r1;r11=r1;r12=r1;
r13=r1;r14=r1;r15=r1;r16=r1;

rr1=r1;rr2=r1;rr3=r1;rr4=r1;


f1_Sol=complex(zeros(1,ntC,iq,'double'));
f2_Sol=f1_Sol;f3_Sol=f1_Sol;f4_Sol=f1_Sol;
f1_Solv=complex(zeros(1,ntC,iq,'double'));
f2_Solv=f1_Solv;

[tau_1D,tau_2D,wDf,wDi]=ndgrid(tauD,tauD,E_vib,E_vib);
[tau0,wCf,wCi]=ndgrid(tauC,E_vib,E_vib);
[~,wSf,wSi]=ndgrid(tauC,wsolv,wsolv);
wD=wDf-wDi;
wC=wCf-wCi;
wS=wSf-wSi;
% [tau_1,tau_2]=meshgrid(tauD);
Lp=1./(w_L-weg-w+1i*gamma_eg);
Lm=1./(-w_L+weg-w+1i*gamma_eg);
Lc1=exp((-1i*wD*r2w-damp).*tau_1D);
Lc2=exp((-1i*wD*r2w-damp).*tau_2D);
Lc0=exp((-1i*wC*r2w-damp).*tau0);
LcS=exp((-1i*wS*r2w-damp).*tau0);
%% Loop over initial state m => assume m is in the ground state m=1, 0
% quanta.
for m=1:1
    % Loop over vibrational states n
    parfor n=1:iq
        if abs(n-m)==1
            %
            f1_Solv(:,:,n)=f1_Solv(:,:,n)+boltz_pop(m)*LcS(:,n,m).';
            f2_Solv(:,:,n)=f2_Solv(:,:,n)+boltz_pop(m)*LcS(:,m,n).';
            %
        end
        % Loop over vibrational states k
        for k=1:iq
            % Loop over vibrational states l
            for l=1:iq
                %
                % NOTE OVERLAP INEGRALS ARE STORED WITH EXCITED STATE INDEX FIRST
                %
                if k~=m
                  f1_Sol(:,:,n)=f1_Sol(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(l,m)...
                        *Lp(n,m)...
                        *Lc0(:,k,m).'...
                        *Lp(l,m);
                    %
                    f2_Sol(:,:,n)=f2_Sol(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(l,k)...
                        *Lm(m,n)...
                        *Lc0(:,m,k).'...
                        *Lp(l,k);
                    %
                end
                %
                if k~=n
                    f3_Sol(:,:,n)=f3_Sol(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(n,l)...
                        *Lp(n,m)...
                        *Lc0(:,n,k).'...
                        *Lp(n,l);
                    %
                    f4_Sol(:,:,n)=f4_Sol(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(k,l)...
                        *Lm(m,n)...
                        *Lc0(:,k,n).'...
                        *Lp(k,l);
                end
                %
                % Compute fifth order auxillary functions
                % Loop over vibrational states u
                for u=1:iq
                    % Loop over vibrational states v
                    for v=1:iq
                        %
                        if m~=u && m~=k
                            % Auxillary function #1 for fifth order signal
%                             r1(:,:,n)=r1(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(l,u)*ovlp(v,u)*ovlp(v,m)...
%                                 *Lp(n,m)...
%                                 .*exp((-1i*w(k,m)*r2w-damp)*tau_1 )...
%                                 *Lp(l,m)...
%                                 .*exp((-1i*w(u,m)*r2w-gamma_vib*c)*tau_2)...
%                                 *Lp(v,m);
                            r1(:,:,n)=r1(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(l,u)*ovlp(v,u)*ovlp(v,m)...
                                *Lp(n,m)...
                                .*Lc1(:,:,k,m)...
                                *Lp(l,m)...
                                .*Lc2(:,:,u,m)...
                                *Lp(v,m);
                            
                        end
                        %
                        if k~=u && m~=k
                            % Auxillary function #2 for fifth order signal
%                             r2(:,:,n)=r2(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(l,u)*ovlp(v,k)*ovlp(v,u)...
%                                 *Lp(n,m)...
%                                 .*exp((-1i*w(k,m)*r2w-damp)*tau_1 )...
%                                 *Lm(k,l)...
%                                 .*exp((-1i*w(k,u)*r2w-gamma_vib*c)*tau_2)...
%                                 *Lp(v,u);
                            r2(:,:,n)=r2(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(l,u)*ovlp(v,k)*ovlp(v,u)...
                                *Lp(n,m)...
                                .*Lc1(:,:,k,m)...
                                *Lm(k,l)...
                                .*Lc2(:,:,k,u)...
                                *Lp(v,u);
                        end
                        %
                        if m~=u && m~=k
                            % Auxillary function #3 for fifth order signal
%                             r3(:,:,n)=r3(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(l,u)*ovlp(v,m)*ovlp(v,u)...
%                                 *Lm(m,n)...
%                                 .*exp((-1i*w(m,k)*r2w-damp)*tau_1 )...
%                                 *Lm(m,l)...
%                                 .*exp((-1i*w(m,u)*r2w-gamma_vib*c)*tau_2)...
%                                 *Lp(v,u);
                            r3(:,:,n)=r3(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(l,u)*ovlp(v,m)*ovlp(v,u)...
                                *Lm(m,n)...
                                .*Lc1(:,:,m,k)...
                                *Lm(m,l)...
                                .*Lc2(:,:,m,u)...
                                *Lp(v,u);
                        end
                        %
                        if k~=u && m~=k
                            % Auxillary function #4 for fifth order signal
%                             r4(:,:,n)=r4(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(l,u)*ovlp(v,u)*ovlp(v,k)...
%                                 *Lm(m,n)...
%                                 .*exp((-1i*w(m,k)*r2w-damp)*tau_1 )...
%                                 *Lp(l,k)...
%                                 .*exp((-1i*w(u,k)*r2w-gamma_vib*c)*tau_2)...
%                                 *Lp(v,k);
                            r4(:,:,n)=r4(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(l,u)*ovlp(v,u)*ovlp(v,k)...
                                *Lm(m,n)...
                                .*Lc1(:,:,m,k)...
                                *Lp(l,k)...
                                .*Lc2(:,:,u,k)...
                                *Lp(v,k);
                        end
                        %
                        %
                        if true
                            if k~=u && n~=k
                                % Auxillary function #5 for fifth order signal
%                                 r5(:,:,n)=r5(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(u,l)*ovlp(k,v)*ovlp(u,v)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(n,k)*r2w-damp)*tau_1 )...
%                                     *Lm(l,k)...
%                                     .*exp((-1i*w(u,k)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(u,v);
                                r5(:,:,n)=r5(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(u,l)*ovlp(k,v)*ovlp(u,v)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,n,k)...
                                    *Lm(l,k)...
                                    .*Lc2(:,:,u,k)...
                                    *Lp(u,v);
                            end
                            %
                            if n~=u && n~=k
                                % Auxillary function #6 for fifth order signal
%                                 r6(:,:,n)=r6(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(u,l)*ovlp(u,v)*ovlp(n,v)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(n,k)*r2w-damp)*tau_1 )...
%                                     *Lp(n,l)...
%                                     .*exp((-1i*w(n,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(n,v);
                                r6(:,:,n)=r6(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(u,l)*ovlp(u,v)*ovlp(n,v)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,n,k)...
                                    *Lp(n,l)...
                                    .*Lc2(:,:,n,u)...
                                    *Lp(n,v);
                                %
                                % Auxillary function #7 for fifth order signal
%                                 r7(:,:,n)=r7(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(u,l)*ovlp(n,v)*ovlp(u,v)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(k,n)*r2w-damp)*tau_1 )...
%                                     *Lm(l,n)...
%                                     .*exp((-1i*w(u,n)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(u,v);
                                r7(:,:,n)=r7(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(u,l)*ovlp(n,v)*ovlp(u,v)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,k,n)...
                                    *Lm(l,n)...
                                    .*Lc2(:,:,u,n)...
                                    *Lp(u,v);
                            end
                            %
                            if k~=u && n~=k
                                % Auxillary function #8 for fifth order signal
%                                 r8(:,:,n)=r8(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(u,l)*ovlp(u,v)*ovlp(k,v)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(k,n)*r2w-damp)*tau_1 )...
%                                     *Lp(k,l)...
%                                     .*exp((-1i*w(k,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(k,v);
                                r8(:,:,n)=r8(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(u,l)*ovlp(u,v)*ovlp(k,v)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,k,n)...
                                    *Lp(k,l)...
                                    .*Lc2(:,:,k,u)...
                                    *Lp(k,v);
                            end
                            %
                            if l~=u && m~=k
                                % Auxillary function #9 for fifth order signal
%                                 r9(:,:,n)=r9(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(u,m)*ovlp(u,v)*ovlp(l,v)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(k,m)*r2w-damp)*tau_1 )...
%                                     *Lp(l,m)...
%                                     .*exp((-1i*w(l,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(l,v);
                                r9(:,:,n)=r9(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(u,m)*ovlp(u,v)*ovlp(l,v)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,k,m)...
                                    *Lp(l,m)...
                                    .*Lc2(:,:,l,u)...
                                    *Lp(l,v);
                                %
                                % Auxillary function #10 for fifth order signal
%                                 r10(:,:,n)=r10(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(u,k)*ovlp(l,v)*ovlp(u,v)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(k,m)*r2w-damp)*tau_1 )...
%                                     *Lm(k,l)...
%                                     .*exp((-1i*w(u,l)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(u,v);
                                r10(:,:,n)=r10(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(u,k)*ovlp(l,v)*ovlp(u,v)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,k,m)...
                                    *Lm(k,l)...
                                    .*Lc2(:,:,u,l)...
                                    *Lp(u,v);
                                %
                                % Auxillary function #11 for fifth order signal
%                                 r11(:,:,n)=r11(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(u,k)*ovlp(u,v)*ovlp(l,v)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(m,k)*r2w-damp)*tau_1 )...
%                                     *Lp(l,k)...
%                                     .*exp((-1i*w(l,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(l,v);
                                r11(:,:,n)=r11(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,m)*ovlp(u,k)*ovlp(u,v)*ovlp(l,v)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,m,k)...
                                    *Lp(l,k)...
                                    .*Lc2(:,:,l,u)...
                                    *Lp(l,v);
                                %
                                % Auxillary function #12 for fifth order signal
%                                 r12(:,:,n)=r12(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(u,m)*ovlp(l,v)*ovlp(u,v)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(m,k)*r2w-damp)*tau_1 )...
%                                     *Lm(m,l)...
%                                     .*exp((-1i*w(u,l)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(u,v);
                                r12(:,:,n)=r12(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(n,k)*ovlp(l,k)*ovlp(u,m)*ovlp(l,v)*ovlp(u,v)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,m,k)...
                                    *Lm(m,l)...
                                    .*Lc2(:,:,u,l)...
                                    *Lp(u,v);
                            end
                            if l~=u && n~=k
                                %
                                % Auxillary function #13 for fifth order signal
%                                 r13(:,:,n)=r13(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(k,u)*ovlp(v,l)*ovlp(v,u)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(n,k)*r2w-damp)*tau_1 )...
%                                     *Lm(l,k)...
%                                     .*exp((-1i*w(l,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(v,u);
                                r13(:,:,n)=r13(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(k,u)*ovlp(v,l)*ovlp(v,u)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,n,k)...
                                    *Lm(l,k)...
                                    .*Lc2(:,:,l,u)...
                                    *Lp(v,u);
                                %
                                % Auxillary function #14 for fifth order signal
%                                 r14(:,:,n)=r14(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(n,u)*ovlp(v,u)*ovlp(v,l)...
%                                     *Lp(n,m)...
%                                     .*exp((-1i*w(n,k)*r2w-damp)*tau_1 )...
%                                     *Lp(n,l)...
%                                     .*exp((-1i*w(u,l)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(v,l);
                                r14(:,:,n)=r14(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(n,u)*ovlp(v,u)*ovlp(v,l)...
                                    *Lp(n,m)...
                                    .*Lc1(:,:,n,k)...
                                    *Lp(n,l)...
                                    .*Lc2(:,:,u,l)...
                                    *Lp(v,l);
                                %
                                % Auxillary function #15 for fifth order signal
%                                 r15(:,:,n)=r15(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(n,u)*ovlp(v,l)*ovlp(v,u)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(k,n)*r2w-damp)*tau_1 )...
%                                     *Lm(l,n)...
%                                     .*exp((-1i*w(l,u)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(v,u);
                                r15(:,:,n)=r15(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(k,l)*ovlp(n,u)*ovlp(v,l)*ovlp(v,u)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,k,n)...
                                    *Lm(l,n)...
                                    .*Lc2(:,:,l,u)...
                                    *Lp(v,u);
                                %
                                % Auxillary function #16 for fifth order signal
%                                 r16(:,:,n)=r16(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(k,u)*ovlp(v,u)*ovlp(v,l)...
%                                     *Lm(m,n)...
%                                     .*exp((-1i*w(k,n)*r2w-damp)*tau_1 )...
%                                     *Lp(k,l)...
%                                     .*exp((-1i*w(u,l)*r2w-gamma_vib*c)*tau_2)...
%                                     *Lp(v,l);
                                r16(:,:,n)=r16(:,:,n)+boltz_pop(m)*ovlp(n,m)*ovlp(k,m)*ovlp(n,l)*ovlp(k,u)*ovlp(v,u)*ovlp(v,l)...
                                    *Lm(m,n)...
                                    .*Lc1(:,:,k,n)...
                                    *Lp(k,l)...
                                    .*Lc2(:,:,u,l)...
                                    *Lp(v,l);
                            end
                        end
                        %
                        
                        
                        
                    end % End loop over vibrational states v
                end % End loop over vibrational states u
                
            end % End loop over vibrational state l
        end % End loop over vibrational states k
    end % End loop over vibrational states n
    f1_Sol=sum(f1_Sol,3);f2_Sol=sum(f2_Sol,3);f3_Sol=sum(f3_Sol,3);f4_Sol=sum(f4_Sol,3);
    f1_Solv=sum(f1_Solv,3);f2_Solv=sum(f2_Solv,3);
    r1=sum(r1,3);r2=sum(r2,3);r3=sum(r3,3);r4=sum(r4,3);
    r5=sum(r5,3);r6=sum(r6,3);r7=sum(r7,3);r8=sum(r8,3);
    r9=sum(r9,3);r10=sum(r10,3);r11=sum(r11,3);r12=sum(r12,3);
    r13=sum(r13,3);r14=sum(r14,3);r15=sum(r15,3);r16=sum(r16,3);
end % End loop over initial state

%
% direct=-0.09*(r1+r2+r3+r4);
direct=-((r1+r2+r3+r4)+(r5+r6+r7+r8)...
    +(r9+r10+r11+r12)+(r13+r14+r15+r16));%0.09*
% direct=direct-mean(mean(direct));
%
% COMPUTE 2D CASCADES
%
% nt1=length(kjf)/2;
ntC=nt;

% direct=direct(1:nt1,1:nt1);
%
% seq1=-7.9e-4*1i*(f1_1+f2_1)*(f1_2+f2_2);
% seq2=-2.7e-3*1i*(conj(f1_1)+conj(f2_1))*(f1_2+f2_2);
% seq1=-7.9e-4*1i*(f1_1+f2_1+f3_1+f4_1)...
%     *(f1_2+f2_2+f3_2+f4_2);
% seq2=-2.7e-3*1i*(conj(f1_1)+conj(f2_1)+conj(f3_1)+conj(f4_1))...
%     *(f1_2+f2_2+f3_2+f4_2);

for t_1=1:ntC
for t_2=1:ntC
seq1(t_2,t_1)=-1i*(f1_Solv(t_1)+f2_Solv(t_1)+...
    conj(f1_Solv(t_1))+conj(f2_Solv(t_1)))...
    *(f1_Sol(t_2)+f2_Sol(t_2)+f3_Sol(t_2)+f4_Sol(t_2));
seq2(t_2,t_1)=-1i*(f1_Sol(t_1)+f2_Sol(t_1)+f3_Sol(t_1)+f4_Sol(t_1)+...
    conj(f1_Sol(t_1))+conj(f2_Sol(t_1))+conj(f3_Sol(t_1))+conj(f4_Sol(t_1)))...
    *(f1_Solv(t_2)+f2_Solv(t_2));
par1(t_2,t_1)=-2i*(f1_Solv(t_2)+f2_Solv(t_2))...
    *(f1_Sol(t_1+t_2)+f2_Sol(t_1+t_2)+f3_Sol(t_1+t_2)+f4_Sol(t_1+t_2));
par2(t_2,t_1)=-2i*(f1_Sol(t_2)+f2_Sol(t_2)+f3_Sol(t_2)+f4_Sol(t_2))...
    *(f1_Solv(t_1+t_2)+f2_Solv(t_1+t_2));
end
end


% for t_1=1:ntC
% for t_2=1:ntC
% seq1(t_2,t_1)=-1i*(f1_Sol(t_1)+f2_Sol(t_1))*(f1_Sol(t_2)+f2_Sol(t_2));
% seq2(t_2,t_1)=-1i*(conj(f1_Sol(t_2))+conj(f2_Sol(t_2)))*(conj(f1_Solv(t_1))+conj(f2_Solv(t_1)));
% par1(t_2,t_1)=-1i*(f1_Sol(t_1+t_2)+f2_Sol(t_1+t_2)+f3_Sol(t_1+t_2)+f4_Sol(t_1+t_2));
% par2(t_2,t_1)=-1i*(f1_Sol(t_2)+f2_Sol(t_2)+f3_Sol(t_2)+f4_Sol(t_2));
% end
% end



seq=seq1(1:ntC,1:ntC)+seq2(1:ntC,1:ntC);
par=par1+par2;
cascade=seq+par;

% time=tau_1(1:nt1);
% wt=exp(-2*pi*1i*omega*c*time);
% [wt1,wt2]=meshgrid(wt,wt);
dw=1/ntC;
w=(-1/2:dw:(1/2-dw))/dt/c;
[~,iomega]=min(abs(w-wvib));

cas2=abs(fftshift(fft2(cascade)));
dir2=abs(fftshift(fft2(direct)));
cas=cas2(iomega,iomega);
dir=dir2(iomega,iomega);
ratio=cas/dir;
% cascade=cascade-mean(mean(cascade));

%
% FOURIER TRANSFORM tau_1 & tau_2
%
% seq=fftshift(fft2(seq));
% par=fftshift(fft2(par));
% cascade2d=fftshift(fft2(cascade));
% direct2d=fftshift(fft2(direct));
% ratio=abs(cascade2d(omega,omega)/abs(direct2d(omega,omega);
% test=direct;

% figure;
% subplot(1,2,1);contour(w,w,abs(cas2),50);colorbar
% subplot(1,2,2);contour(w,w,abs(dir2),50);colorbar