function [direct,seq2,e3,tau,wrs] = response2_Tuner(wviball,fcall,wvib,w_ap)
ev=wviball;
%
% COMPUTE BOLTZMANN POPULATIONS
%
[ij,ii]=size(wviball);
kT=200;
pf(1:ii)=exp(-wviball(1:ii)/kT);pf=sum(pf);
boltz(1:ii)=exp(-wviball(1:ii)/kT)/pf;
%
%
%
iq=4;
r2w=0.0001885;
c=3e-5;
weg=20000;
w_rp=w_ap;
bwa=210;
bwb=40;
gameg=1000;
gamvib=10;
tau2=300*c;
damp=0;
%
kj=1:100;
% Frequency signal
wt=w_rp-wvib;%w_rp-(kj-1)*32;
wrs=wt;
% Number of frequency points in spectrum
nw=length(wt);

% wrs(:)=wb-wt;
tau=(kj-1)*100;
nt=length(tau);
% Initialize response functions to 0
r1=zeros(nt,nw,'double');f1A=zeros(nt,nw,'double');
% r1=zeros(nt,nt,'double');f1A=zeros(nt,nt,'double');
r2=r1;r3=r1;r4=r1;r5=r1;r6=r1;r7=r1;r8=r1;
r9=r1;r10=r1;r11=r1;r12=r1;r13=r1;r14=r1;r15=r1;r16=r1;
f1B=f1A;f2A=f1A;f2B=f1A;f3A=f1A;f3B=f1A;f4A=f1A;f4B=f1A;
%
for ii=1:length(tau)
%
for m=1:1  
for n=1:iq 
for k=1:iq 
for l=1:iq
%
% DO FWM PARTS OF CASCADES
% k3-k4+k5
%
% damp=(gamvib)*c;
% if k==m
% damp=0;
% end
if n~=k
f1A(ii,:)=f1A(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,l)...
*1./(wt-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wt-w_rp-(ev(n)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(n)-ev(l))+1i*gameg);
%
f2A(ii,:)=f2A(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,l)...
*1./(-w_rp+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wt-w_rp-(ev(k)-ev(n))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(k)-ev(l))+1i*gameg);
end
%
if m~=k
f3A(ii,:)=f3A(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,m)...
*1./(wt-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wt-w_rp-(ev(k)-ev(m))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(l)-ev(m))+1i*gameg);
end
%
if l~=k
f4A(ii,:)=f4A(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,k)...
*1./(-w_rp+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wt-w_rp-(ev(l)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(m)-ev(k))+1i*gameg);
end
%
if k~=m
f1B(ii,:)=f1B(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,l)...
*1./(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wt-weg-(ev(n)-ev(l))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(n)-ev(k))^2+bwa^2);
%
f2B(ii,:)=f2B(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,l)...
*1./(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wt-weg-(ev(k)-ev(l))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(k)-ev(n))^2+bwa^2);
%
f3B(ii,:)=f3B(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,m)...
*1./(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wt-weg-(ev(l)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(k)-ev(m))^2+bwa^2);
%
f4B(ii,:)=f4B(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,k)...
*1./(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wt-weg-(ev(l)-ev(k))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(m)-ev(k))^2+bwa^2);
end
%
%
%
for u=1:iq
for v=1:iq
%
if m~=u
r1(ii,:)=r1(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,u)*fcall(v,u)*fcall(v,m)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(wt-weg-(ev(l)-ev(m))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(m))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(m))+1i*gameg);
end
%
if k~=u
r2(ii,:)=r2(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,u)*fcall(v,k)*fcall(v,u)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(-w_rp+weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(k)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(u))+1i*gameg);
end
%
if m~=u
r3(ii,:)=r3(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,u)*fcall(v,m)*fcall(v,u)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(-w_rp+weg-(ev(m)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(m)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(u))+1i*gameg);
end
%
if k~=u
r4(ii,:)=r4(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,u)*fcall(v,u)*fcall(v,k)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(wt-weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(k))+1i*gameg);
end
%
if k~=u
r5(ii,:)=r5(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(u,l)*fcall(k,v)*fcall(u,v)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(-w_rp+weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(u)-ev(v))+1i*gameg);
end
%
if n~=u
r6(ii,:)=r6(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(u,l)*fcall(u,v)*fcall(n,v)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(wt-weg-(ev(n)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(n)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(n)-ev(v))+1i*gameg);
end
%
if n~=u
r7(ii,:)=r7(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(u,l)*fcall(n,v)*fcall(u,v)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(-w_rp+weg-(ev(l)-ev(n))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(n))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(u)-ev(v))+1i*gameg);
end
%
if k~=u
r8(ii,:)=r8(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(u,l)*fcall(u,v)*fcall(k,v)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(wt-weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(k)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(k)-ev(v))+1i*gameg);
end
%
if l~=u
r9(ii,:)=r9(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(u,m)*fcall(u,v)*fcall(l,v)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(wt-weg-(ev(l)-ev(m))+1i*gameg)...
*1./(wt-w_rp-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(l)-ev(v))+1i*gameg);
%
r10(ii,:)=r10(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(u,k)*fcall(l,v)*fcall(u,v)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(-w_rp+weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(u)-ev(v))+1i*gameg);
%
r11(ii,:)=r11(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(u,k)*fcall(u,v)*fcall(l,v)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(wt-weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wt-w_rp-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(l)-ev(v))+1i*gameg);
%
r12(ii,:)=r12(ii,:)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(u,m)*fcall(l,v)*fcall(u,v)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(-w_rp+weg-(ev(m)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(u)-ev(v))+1i*gameg);
%
r13(ii,:)=r13(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,u)*fcall(v,l)*fcall(v,u)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(-w_rp+weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wt-w_rp-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(u))+1i*gameg);
%
r14(ii,:)=r14(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,u)*fcall(v,u)*fcall(v,l)...
*1/(w_ap-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(wt-weg-(ev(n)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(l))+1i*gameg);
%
r15(ii,:)=r15(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,u)*fcall(v,l)*fcall(v,u)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(-w_rp+weg-(ev(l)-ev(n))+1i*gameg)...
*1./(wt-w_rp-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(u))+1i*gameg);
%
r16(ii,:)=r16(ii,:)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,u)*fcall(v,u)*fcall(v,l)...
*1/(-w_ap+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(wt-weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wt-w_rp-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wt-weg-(ev(v)-ev(l))+1i*gameg);
end
%
%
%
%
end
end
end
end
end
end
%
end
seq2=-1i^3*(f1A+f2A+f3A+f4A).*(f1B+f2B+f3B+f4B);
e3=-1i*(f1A+f2A+f3A+f4A);
%
% COMPUTE SEQUENTIAL CASCADE
%
direct=(r1+r2+r3+r4)+(r5+r6+r7+r8)+(r9+r10+r11+r12)+(r13+r14+r15+r16);
direct=-direct;
%
%