function [direct,seq2,e3,tau,wrs] = response2(wviball,fcall)
ev=wviball;
%
% COMPUTE BOLTZMANN POPULATIONS
%
[ij,ii]=size(wviball);
kT=200;
pf(1:ii)=exp(-wviball(1:ii)/kT);pf=sum(pf);
boltz(1:ii)=exp(-wviball(1:ii)/kT)/pf;
%
%
%
iq=4;
r2w=0.0001885;
c=3e-5;
weg=22720;%20000;
wa=weg+0;
wb=wa;
bwa=210;
bwb=40;
gameg=3000;%1000;
gamvib=10;
tau2=300*c;
damp=0;
%
kj=1:100;wc(kj)=wb-(kj-1)*32;wrs(kj)=wb-wc(kj);
tau(kj)=(kj-1)*100;
for ii=1:length(tau)
r1(ii,kj)=0;
r2(ii,kj)=0;
r3(ii,kj)=0;
r4(ii,kj)=0;
r5(ii,kj)=0;
r6(ii,kj)=0;
r7(ii,kj)=0;
r8(ii,kj)=0;
r9(ii,kj)=0;
r10(ii,kj)=0;
r11(ii,kj)=0;
r12(ii,kj)=0;
r13(ii,kj)=0;
r14(ii,kj)=0;
r15(ii,kj)=0;
r16(ii,kj)=0;
f1A(ii,kj)=0;f1B(ii,kj)=0;
f2A(ii,kj)=0;f2B(ii,kj)=0;
f3A(ii,kj)=0;f3B(ii,kj)=0;
f4A(ii,kj)=0;f4B(ii,kj)=0;
end
%
for ii=1:length(tau)
%
for m=1:1  
for n=1:iq 
for k=1:iq 
for l=1:iq
%
% DO FWM PARTS OF CASCADES
% k3-k4+k5
%
% damp=(gamvib)*c;
% if k==m
% damp=0;
% end
if n~=k
f1A(ii,kj)=f1A(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,l)...
*1./(wc(kj)-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wc(kj)-wb-(ev(n)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(n)-ev(l))+1i*gameg);
%
f2A(ii,kj)=f2A(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,l)...
*1./(-wb+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wc(kj)-wb-(ev(k)-ev(n))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(k)-ev(l))+1i*gameg);
end
%
if m~=k
f3A(ii,kj)=f3A(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,m)...
*1./(wc(kj)-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wc(kj)-wb-(ev(k)-ev(m))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(l)-ev(m))+1i*gameg);
end
%
if l~=k
f4A(ii,kj)=f4A(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,k)...
*1./(-wb+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wc(kj)-wb-(ev(l)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(m)-ev(k))+1i*gameg);
end
%
if k~=m
f1B(ii,kj)=f1B(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,l)...
*1./(wa-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wc(kj)-weg-(ev(n)-ev(l))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(n)-ev(k))^2+bwa^2);
%
f2B(ii,kj)=f2B(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,l)...
*1./(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wc(kj)-weg-(ev(k)-ev(l))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(k)-ev(n))^2+bwa^2);
%
f3B(ii,kj)=f3B(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,m)...
*1./(wa-weg-(ev(n)-ev(m))+1i*gameg)...
*1./(wc(kj)-weg-(ev(l)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(k)-ev(m))^2+bwa^2);
%
f4B(ii,kj)=f4B(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,k)...
*1./(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
*1./(wc(kj)-weg-(ev(l)-ev(k))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii))*2*bwa/((ev(m)-ev(k))^2+bwa^2);
end
%
%
%
for u=1:iq
for v=1:iq
%
if m~=u
r1(ii,kj)=r1(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,u)*fcall(v,u)*fcall(v,m)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(l)-ev(m))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(m))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(m))+1i*gameg);
end
%
if k~=u
r2(ii,kj)=r2(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,u)*fcall(v,k)*fcall(v,u)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(-wb+weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(k)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(u))+1i*gameg);
end
%
if m~=u
r3(ii,kj)=r3(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(l,u)*fcall(v,m)*fcall(v,u)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(-wb+weg-(ev(m)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(m)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(u))+1i*gameg);
end
%
if k~=u
r4(ii,kj)=r4(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(l,u)*fcall(v,u)*fcall(v,k)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(k))+1i*gameg);
end
%
if k~=u
r5(ii,kj)=r5(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(u,l)*fcall(k,v)*fcall(u,v)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(-wb+weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(k))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(u)-ev(v))+1i*gameg);
end
%
if n~=u
r6(ii,kj)=r6(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(u,l)*fcall(u,v)*fcall(n,v)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(n)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(n)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(n)-ev(v))+1i*gameg);
end
%
if n~=u
r7(ii,kj)=r7(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(u,l)*fcall(n,v)*fcall(u,v)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(-wb+weg-(ev(l)-ev(n))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(n))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(u)-ev(v))+1i*gameg);
end
%
if k~=u
r8(ii,kj)=r8(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(u,l)*fcall(u,v)*fcall(k,v)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(k)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(k)-ev(v))+1i*gameg);
end
%
if l~=u
r9(ii,kj)=r9(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(u,m)*fcall(u,v)*fcall(l,v)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(l)-ev(m))+1i*gameg)...
*1./(wc(kj)-wb-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(l)-ev(v))+1i*gameg);
%
r10(ii,kj)=r10(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(u,k)*fcall(l,v)*fcall(u,v)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(m))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(m))^2+bwa^2)...
*1./(-wb+weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(u)-ev(v))+1i*gameg);
%
r11(ii,kj)=r11(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,m)*fcall(u,k)*fcall(u,v)*fcall(l,v)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wc(kj)-wb-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(l)-ev(v))+1i*gameg);
%
r12(ii,kj)=r12(ii,kj)+boltz(m)*fcall(n,m)*fcall(n,k)*fcall(l,k)*fcall(u,m)*fcall(l,v)*fcall(u,v)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(m)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(m)-ev(k))^2+bwa^2)...
*1./(-wb+weg-(ev(m)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(u)-ev(v))+1i*gameg);
%
r13(ii,kj)=r13(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,u)*fcall(v,l)*fcall(v,u)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(-wb+weg-(ev(l)-ev(k))+1i*gameg)...
*1./(wc(kj)-wb-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(u))+1i*gameg);
%
r14(ii,kj)=r14(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,u)*fcall(v,u)*fcall(v,l)...
*1/(wa-weg-(ev(n)-ev(m))+1i*gameg)...
.*exp(-1i*(ev(n)-ev(k))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(n)-ev(k))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(n)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(l))+1i*gameg);
%
r15(ii,kj)=r15(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(k,l)*fcall(n,u)*fcall(v,l)*fcall(v,u)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(-wb+weg-(ev(l)-ev(n))+1i*gameg)...
*1./(wc(kj)-wb-(ev(l)-ev(u))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(u))+1i*gameg);
%
r16(ii,kj)=r16(ii,kj)+boltz(m)*fcall(n,m)*fcall(k,m)*fcall(n,l)*fcall(k,u)*fcall(v,u)*fcall(v,l)...
*1/(-wa+weg-(ev(m)-ev(n))+1i*gameg)...
.*exp(-1i*(ev(k)-ev(n))*r2w*tau(ii)-damp*tau(ii) )*2*bwa/((ev(k)-ev(n))^2+bwa^2)...
*1./(wc(kj)-weg-(ev(k)-ev(l))+1i*gameg)...
*1./(wc(kj)-wb-(ev(u)-ev(l))+1i*(gamvib-bwb))*exp(-bwb*tau2*c)...
*1./(wc(kj)-weg-(ev(v)-ev(l))+1i*gameg);
end
%
%
%
%
end
end
end
end
end
end
%
seq2(ii,kj)=-1i^3*(f1A(ii,kj)+f2A(ii,kj)+f3A(ii,kj)+f4A(ii,kj)).*(f1B(ii,kj)+f2B(ii,kj)+f3B(ii,kj)+f4B(ii,kj)    );
e3=-1i*(f1A(ii,kj)+f2A(ii,kj)+f3A(ii,kj)+f4A(ii,kj));
end
%
% COMPUTE SEQUENTIAL CASCADE
%
direct=(r1+r2+r3+r4)+(r5+r6+r7+r8)+(r9+r10+r11+r12)+(r13+r14+r15+r16);
direct=-direct;
%
%